# Generated by Django 4.0.10 on 2024-12-06 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_name', models.CharField(max_length=100)),
                ('artifact_type', models.CharField(choices=[('clothing', 'Clothing'), ('jewelry', 'Jewelry'), ('tool', 'Tool'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('historical_significance', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('cultural_significance', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('contributor', models.CharField(help_text='Name of the person who submitted the artifact', max_length=100)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, help_text="Verifier's name", max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('published', 'Published')], default='pending', help_text='Verification status', max_length=10)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
