# Generated by Django 4.0.10 on 2024-12-28 08:29

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artifacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to=core.helpers.image_path)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.artifacts')),
            ],
        ),
    ]
