# Generated by Django 4.0.10 on 2024-12-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artifactimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactimages',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.artifacts'),
        ),
    ]
