# Generated by Django 4.0.10 on 2025-01-06 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artifactimages_artifact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifactimages',
            options={'verbose_name': 'Artifact Images', 'verbose_name_plural': 'Artifact Images'},
        ),
        migrations.AlterModelOptions(
            name='artifacts',
            options={'verbose_name': 'Artifacts', 'verbose_name_plural': 'Artifacts'},
        ),
        migrations.RemoveField(
            model_name='artifacts',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='artifacts',
            name='vetting_users',
            field=models.ManyToManyField(blank=True, related_name='vetted_artifacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verifier',
            field=models.BooleanField(default=False),
        ),
    ]
