# Generated by Django 4.0.10 on 2025-01-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_artifactimages_options_alter_artifacts_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifacts',
            old_name='vetting_users',
            new_name='verified_by',
        ),
    ]
