# Generated by Django 4.0.10 on 2025-01-07 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_vetting_users_artifacts_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifacts',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='artifacts',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
