# Generated by Django 4.0.10 on 2025-01-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_artifacts_verified_by_artifacts_verified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('draft', 'Draft'), ('vetting', 'Vetting'), ('published', 'Published')], max_length=50, null=True)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('vetting', 'Vetting'), ('published', 'Published')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.artifacts')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
