# Generated by Django 4.0.10 on 2025-01-08 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_artifactstatuslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifactstatuslog',
            options={'verbose_name': 'Artifact Status Log', 'verbose_name_plural': 'Artifact Status Log'},
        ),
        migrations.AddField(
            model_name='artifacts',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artifacts',
            name='vetted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artifacts',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifacts',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('published', 'Published')], default='draft', help_text='Verification status', max_length=10),
        ),
        migrations.AlterField(
            model_name='artifactstatuslog',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('vetting', 'Vetting'), ('verified', 'Verified'), ('published', 'Published')], max_length=50),
        ),
        migrations.AlterField(
            model_name='artifactstatuslog',
            name='previous_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('vetting', 'Vetting'), ('verified', 'Verified'), ('published', 'Published')], max_length=50, null=True),
        ),
    ]
