# Generated by Django 4.0.10 on 2025-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_artifactstatuslog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vetter',
            field=models.BooleanField(default=False),
        ),
    ]
