# Generated by Django 4.0.10 on 2025-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_is_publisher_user_is_vetter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifacts',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('vetting', 'Vetting'), ('verified', 'Verified'), ('published', 'Published')], default='draft', help_text='Verification status', max_length=10),
        ),
    ]
