# Generated by Django 4.0.10 on 2025-01-21 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_artifacts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifacts',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artifacts',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artifacts',
            name='vetted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
