# Generated by Django 4.0.10 on 2025-11-04 07:34

import core.helpers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Pending Verification'), ('vetting', 'Vetting'), ('verified', 'Verified'), ('published', 'Published')], default='pending', max_length=20)),
                ('category', models.CharField(choices=[('heritage', 'Heritage'), ('language', 'Language'), ('botanical', 'Botanical'), ('tribal', 'Tribal'), ('migration', 'Migration')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('population_density', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('migration_route', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unesco', models.BooleanField(default=False)),
                ('undp', models.BooleanField(default=False)),
                ('unicef', models.BooleanField(default=False)),
                ('local_context', models.TextField(blank=True)),
                ('indigenous_system', models.CharField(blank=True, max_length=255)),
                ('rights', models.TextField(blank=True)),
                ('ip_metadata', models.TextField(blank=True)),
                ('sensitivity_level', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('closed', 'Closed')], default='public', max_length=20)),
                ('access_protocol', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policies', 'verbose_name_plural': 'Policies'},
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('is_override', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='core.heritagesite')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_verifier_count', models.PositiveIntegerField(default=2, help_text='Number of verifier votes required to change status')),
                ('verifiers', models.ManyToManyField(help_text='Users who can verify sites', limit_choices_to={'groups__name': 'verifiers'}, related_name='verifier_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('version', models.CharField(blank=True, default='v1.0', max_length=20, null=True)),
                ('knowledge_category', models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('policy', 'Policy'), ('procedure', 'Procedure'), ('compliance', 'Compliance'), ('general', 'General')], default='general', max_length=100)),
                ('document_type', models.CharField(blank=True, choices=[('article', 'Article'), ('conference_paper', 'Conference paper'), ('research_paper', 'Research paper'), ('book', 'Book'), ('chapter', 'Chapter')], max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.helpers.document_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Pending Verification'), ('vetting', 'Vetting'), ('verified', 'Verified'), ('published', 'Published')], default='draft', help_text='Verification status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_knowledge', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_department', to='core.department')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_knowledge', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_knowledge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Base',
            },
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_metadata', to='core.sitemetadata'),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.sitesettings'),
        ),
        migrations.CreateModel(
            name='SiteVerificationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('reject', 'Reject'), ('approve', 'Approve')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_verifications', to='core.heritagesite')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_verifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('site', 'verifier')},
            },
        ),
    ]
