# Generated by Django 4.0.10 on 2025-01-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_artifacts_published_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifacts',
            name='contributor',
        ),
        migrations.AlterField(
            model_name='artifacts',
            name='status',
            field=models.CharField(choices=[('draft', 'Pending Verification'), ('vetting', 'Vetting'), ('verified', 'Verified'), ('published', 'Published')], default='draft', help_text='Verification status', max_length=10),
        ),
    ]
