# Generated by Django 4.0.10 on 2025-11-04 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_heritagesite_sitemetadata_alter_policy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_site', to=settings.AUTH_USER_MODEL),
        ),
    ]
