# Generated by Django 4.0.10 on 2025-11-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_heritagesite_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heritagesite',
            options={'ordering': ['-date_created'], 'permissions': [('can_verify_site', 'Can verify sites'), ('can_override_verification', 'Can override verification status')]},
        ),
        migrations.AddIndex(
            model_name='heritagesite',
            index=models.Index(fields=['status', 'category'], name='core_herita_status_9246b3_idx'),
        ),
        migrations.AddIndex(
            model_name='heritagesite',
            index=models.Index(fields=['latitude', 'longitude'], name='core_herita_latitud_fc4cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='heritagesite',
            index=models.Index(fields=['-date_created'], name='core_herita_date_cr_2c1b0b_idx'),
        ),
    ]
