# Generated by Django 4.0.10 on 2025-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_heritagesite_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='siteverificationvote',
            index=models.Index(fields=['site', 'vote'], name='core_siteve_site_id_462705_idx'),
        ),
    ]
