# Generated by Django 4.0.10 on 2025-11-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_siteverificationvote_core_siteve_site_id_462705_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteverificationvote',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_verification_vote', to='core.heritagesite'),
        ),
    ]
