# Generated by Django 4.0.10 on 2025-11-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_siteverificationvote_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritagesite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
