# Generated by Django 4.0.10 on 2025-11-06 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_heritagesite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteverificationvote',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_verification_verifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
