# Generated by Django 4.0.10 on 2025-11-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_siteimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimages',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
