# Generated by Django 4.0.10 on 2025-11-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_siteimages_uploaded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteimages',
            options={'verbose_name': 'Site Images', 'verbose_name_plural': 'Site Images'},
        ),
    ]
